Traceback (most recent call last):
  File "/home/thomasl/mambaforge/envs/py311/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/thomasl/mambaforge/envs/py311/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomasl/mambaforge/envs/py311/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomasl/mambaforge/envs/py311/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/thomasl/mambaforge/envs/py311/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/thomasl/mambaforge/envs/py311/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/thomasl/mambaforge/envs/py311/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import xarray as xr
import numpy as np
from copy import copy

import pyresample as pr

from matplotlib import pylab as plt
import cmocean
import matplotlib

from sirrdp import rrdp_file
from pmr_sic import tiepoints as tp

input_test_card = 'sceps_polar_1'
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 11[0m
[1;32m      8[0m [38;5;28;01mimport[39;00m [38;5;21;01mcmocean[39;00m
[1;32m      9[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m
[0;32m---> 11[0m [38;5;28;01mfrom[39;00m [38;5;21;01msirrdp[39;00m [38;5;28;01mimport[39;00m rrdp_file
[1;32m     12[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpmr_sic[39;00m [38;5;28;01mimport[39;00m tiepoints [38;5;28;01mas[39;00m tp
[1;32m     14[0m input_test_card [38;5;241m=[39m [38;5;124m'[39m[38;5;124msceps_polar_1[39m[38;5;124m'[39m

[0;31mModuleNotFoundError[0m: No module named 'sirrdp'

